server:
  port: 8080
  servlet:
    context-path: /backend
polar:
  client-id: ${POLAR_CLIENT_ID}
  client-secret: ${POLAR_CLIENT_SECRET}
  redirect-uri: ${POLAR_REDIRECT_URI}
security:
  auth-token-validity-duration-hours: 1
  security-key: abc123!
spring:
  application:
    name: healthtraq
  datasource:
    url: jdbc:postgresql://postgresql-dev.default.svc.cluster.local:5432/healthtraq_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      # This is fucking insane, but we have also very limited time
      ddl-auto: update